groups:
- name: example
  rules:
  - alert: AppDown
    expr: up == 0
    for: 5m
    labels:
      severity: warn
    annotations:
      summary: "App is down"
      description: "prometheus has detected the application is not running for 5 minutes."
  
  - alert: APIHightLatency:5min
    expr: sum(rate(http_server_requests_seconds_sum{job="project1"}[5m])) / sum(rate(http_server_requests_seconds_count{job="project1"}[5m])) > 0.0002
    labels:
      severity: warn
    annotations:
      summary: "5min latency too high"
      description: "project1 application is taking too long to handle requests in a 5 minute range"

  - alert: APIHightLatency:15min
    expr: sum(rate(http_server_requests_seconds_sum{job="project1"}[15m])) / sum(rate(http_server_requests_seconds_count{job="project1"}[15m])) > 0.2
    labels:
      severity: warn
    annotations:
      summary: "15min latency too high"
      description: "project1 application is taking too long to handle requests in a 15 minute range"

  - alert: APIHightLatency:30min
    expr: sum(rate(http_server_requests_seconds_sum{job="project1"}[30m])) / sum(rate(http_server_requests_seconds_count{job="project1"}[30m])) > 0.2
    labels:
      severity: warn
    annotations:
      summary: "30min latency too high"
      description: "project1 application is taking too long to handle requests in a 30 minute range"

  - alert: APIHightLatency:1hour
    expr: sum(rate(http_server_requests_seconds_sum{job="project1"}[1h])) / sum(rate(http_server_requests_seconds_count{job="project1"}[1h])) > 0.2
    labels:
      severity: warn
    annotations:
      summary: "1hour latency too high"
      description: "project1 application is taking too long to handle requests in a 1 hour range"